before_install:
- sudo apt-get -qq update && sudo apt-get install -y --no-install-recommends latexmk
  texlive-fonts-extra texlive-fonts-recommended texlive-latex-base texlive-latex-extra
  texlive-latex-recommended
script:
- mkdir _build
- latexmk -pdf -outdir=_build cs302S2019_syllabus.tex
deploy:
  provider: releases
  api_key:
    secure: gtl+Pald1+ez4KpevsT+HqgDi3aYcNE92uApg9yDIMV/0ILFeMiy7jjjRni1a0r/fQIAvg8oST6T9yuz7qYqGR5ykwAdkxk8kXhvYSVXme2BtFPjcM9hRZl4f5Av9dW2bmYt7mnQKzM9TMzrhxix3a2ejyf0jZqn3sJ0FofpdxCAmE4u9IThi7fOmaL7b6mdeJ12DmgfJhLkr9UPbg+Wxl5y0e6NJWKxdQX1S1rMwa4veAS266O7xBot7CkqZAEx0IFoJV4mgDrXp6dztpRIrhQ449kB62c+P1CHqCf01T5Unvy+dphi/SwXWUMr1yIi4o+ol8f+es1KCjFBYtqA0L8IkmAlPQkuiQpGAg0p9KPhU8iQk4K2fBWMuOeGUMlsyxq0CpeELCo/ZWVAxHFfvhsaED/Bjk0SvM8gc9bt3xQpgp9gbl6CiyfSeqqN2Ckuehcc9rrA8bdXuleg4kZmjoDpjjLtSnAj4FnOpQOH8Glh8CTzotBrxUX6Q5LSR8ydpsQ+cIvEJZx+ayyn/aq58CQCQEYqSc0j1UqR8DfdQT8gVVxtlqNQgBooY3GvsUMtZR1lSYzDkTFZPfDRLeW8/w2wubYQxssISr0xbOKZXzMMqoRw14RvPZTRN9rbIHAPaqSCy+VYwgw4E8jJB235i2hpU4pdgU1rRXtWUS+kfRU=
  file: _build/cs302S2019_syllabus.pdf
  skip_cleanup: true
  on:
    tags: true
